# Generated by Django 4.2.7 on 2023-11-30 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='Имя пользователя')),
                ('phone', models.CharField(max_length=64, verbose_name='Номер телефона(должн начинаться с +')),
                ('api_id', models.CharField(max_length=16, verbose_name='id API Telegram')),
                ('api_hash', models.CharField(max_length=64, verbose_name='hash API Telegram')),
                ('last_send_message', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки последнего сообщения')),
                ('can_send_message', models.BooleanField(default=True, verbose_name='Можно ли отправить сообщение')),
                ('is_activate', models.BooleanField(default=False, verbose_name='Активирована ли сессия')),
            ],
        ),
        migrations.CreateModel(
            name='Rare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название редкости')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooldown', models.PositiveIntegerField(default=15, verbose_name='Частота отправки сообщений')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=8192, verbose_name='Текст сообщения')),
                ('rare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models.rare', verbose_name='Редкость')),
            ],
        ),
    ]
